services:
  rabbimtmq:
    container_name: rabbimtmq2
    image: rabbitmq:3.13.0-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=curso
